# FAME Smart Flasher - Windows Build Script
# Copyright 2025 Fyrby Additive Manufacturing & Engineering
# SPDX-License-Identifier: Proprietary

param(
    [switch]$Release,
    [switch]$Installer,
    [switch]$Clean
)

$ErrorActionPreference = "Stop"
$ProjectDir = $PSScriptRoot
$ProjectFile = Join-Path $ProjectDir "FAMESmartFlasher.csproj"
$Configuration = if ($Release) { "Release" } else { "Debug" }
$OutputDir = Join-Path $ProjectDir "bin\$Configuration\net8.0-windows"
$PublishDir = Join-Path $ProjectDir "publish"
$InstallerDir = Join-Path $ProjectDir "installer"

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "FAME Smart Flasher - Build Script" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Clean if requested
if ($Clean) {
    Write-Host "Cleaning build artifacts..." -ForegroundColor Yellow
    if (Test-Path (Join-Path $ProjectDir "bin")) {
        Remove-Item -Recurse -Force (Join-Path $ProjectDir "bin")
    }
    if (Test-Path (Join-Path $ProjectDir "obj")) {
        Remove-Item -Recurse -Force (Join-Path $ProjectDir "obj")
    }
    if (Test-Path $PublishDir) {
        Remove-Item -Recurse -Force $PublishDir
    }
    Write-Host "Clean complete." -ForegroundColor Green
    Write-Host ""
}

# Restore packages
Write-Host "Restoring NuGet packages..." -ForegroundColor Yellow
dotnet restore $ProjectFile
if ($LASTEXITCODE -ne 0) {
    Write-Host "Restore failed!" -ForegroundColor Red
    exit 1
}
Write-Host "Restore complete." -ForegroundColor Green
Write-Host ""

# Build
Write-Host "Building $Configuration configuration..." -ForegroundColor Yellow
dotnet build $ProjectFile -c $Configuration --no-restore
if ($LASTEXITCODE -ne 0) {
    Write-Host "Build failed!" -ForegroundColor Red
    exit 1
}
Write-Host "Build complete." -ForegroundColor Green
Write-Host ""

# Publish self-contained if Release
if ($Release) {
    Write-Host "Publishing self-contained application..." -ForegroundColor Yellow

    # Clean publish directory
    if (Test-Path $PublishDir) {
        Remove-Item -Recurse -Force $PublishDir
    }

    # Publish as self-contained single file
    dotnet publish $ProjectFile `
        -c Release `
        -r win-x64 `
        --self-contained true `
        -p:PublishSingleFile=true `
        -p:IncludeNativeLibrariesForSelfExtract=true `
        -p:EnableCompressionInSingleFile=true `
        -o $PublishDir

    if ($LASTEXITCODE -ne 0) {
        Write-Host "Publish failed!" -ForegroundColor Red
        exit 1
    }

    Write-Host "Publish complete." -ForegroundColor Green
    Write-Host "Output: $PublishDir" -ForegroundColor Gray
    Write-Host ""
}

# Create installer if requested
if ($Installer) {
    Write-Host "Creating installer..." -ForegroundColor Yellow

    # Check for Inno Setup
    $InnoSetupPath = @(
        "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe",
        "${env:ProgramFiles}\Inno Setup 6\ISCC.exe",
        "C:\Program Files (x86)\Inno Setup 6\ISCC.exe",
        "C:\Program Files\Inno Setup 6\ISCC.exe"
    ) | Where-Object { Test-Path $_ } | Select-Object -First 1

    if (-not $InnoSetupPath) {
        Write-Host "Inno Setup 6 not found!" -ForegroundColor Red
        Write-Host "Please install Inno Setup 6 from: https://jrsoftware.org/isinfo.php" -ForegroundColor Yellow
        Write-Host ""
        Write-Host "Alternative: You can distribute the self-contained exe directly:" -ForegroundColor Cyan
        Write-Host "  $PublishDir\FAMESmartFlasher.exe" -ForegroundColor Gray
        exit 1
    }

    # Ensure we have published files
    if (-not (Test-Path "$PublishDir\FAMESmartFlasher.exe")) {
        Write-Host "Published files not found. Running publish first..." -ForegroundColor Yellow
        & $PSCommandPath -Release
    }

    # Create installer directory
    if (-not (Test-Path $InstallerDir)) {
        New-Item -ItemType Directory -Path $InstallerDir | Out-Null
    }

    # Create Inno Setup script
    $IssFile = Join-Path $InstallerDir "setup.iss"
    $IssContent = @"
; FAME Smart Flasher Installer Script
; Generated by build.ps1

#define MyAppName "FAME Smart Flasher"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "Fyrby Additive Manufacturing & Engineering"
#define MyAppURL "https://fyrby.com"
#define MyAppExeName "FAMESmartFlasher.exe"

[Setup]
AppId={{8A7B9C3D-4E5F-6A7B-8C9D-0E1F2A3B4C5D}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
LicenseFile=
OutputDir=$InstallerDir
OutputBaseFilename=FAMESmartFlasher-Setup-{#MyAppVersion}
Compression=lzma
SolidCompression=yes
WizardStyle=modern
ArchitecturesInstallIn64BitMode=x64compatible

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "$PublishDir\FAMESmartFlasher.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "$PublishDir\*.dll"; DestDir: "{app}"; Flags: ignoreversion skipifsourcedoesntexist
Source: "$PublishDir\*.json"; DestDir: "{app}"; Flags: ignoreversion skipifsourcedoesntexist

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
"@

    # Fix paths for Inno Setup (use forward slashes or escaped backslashes)
    $IssContent = $IssContent -replace '\\', '\\'

    Set-Content -Path $IssFile -Value $IssContent -Encoding UTF8

    Write-Host "Running Inno Setup compiler..." -ForegroundColor Yellow
    & $InnoSetupPath $IssFile

    if ($LASTEXITCODE -ne 0) {
        Write-Host "Installer creation failed!" -ForegroundColor Red
        exit 1
    }

    Write-Host "Installer created successfully!" -ForegroundColor Green
    Write-Host "Output: $InstallerDir\FAMESmartFlasher-Setup-1.0.0.exe" -ForegroundColor Gray
    Write-Host ""
}

# Summary
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Build Summary" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Configuration: $Configuration" -ForegroundColor Gray

if ($Release) {
    Write-Host "Published to: $PublishDir" -ForegroundColor Gray
    $ExeSize = (Get-Item "$PublishDir\FAMESmartFlasher.exe" -ErrorAction SilentlyContinue).Length
    if ($ExeSize) {
        Write-Host "Executable size: $([math]::Round($ExeSize / 1MB, 2)) MB" -ForegroundColor Gray
    }
}

if ($Installer -and (Test-Path "$InstallerDir\FAMESmartFlasher-Setup-1.0.0.exe")) {
    $InstallerSize = (Get-Item "$InstallerDir\FAMESmartFlasher-Setup-1.0.0.exe").Length
    Write-Host "Installer size: $([math]::Round($InstallerSize / 1MB, 2)) MB" -ForegroundColor Gray
}

Write-Host ""
Write-Host "Done!" -ForegroundColor Green
